server:
  port: 8067
  servlet:
    context-path: /certabotNFe

spring:
  application:
    name: CertaBotNFe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:sqlserver://192.168.0.61;databaseName=CertaBotNFe;encrypt=false;integratedSecurity=false;
    username: giovanni.andrade
    password: gigi1704
