server:
  port: 8061
  servlet:
    context-path: /CertabotNFe

spring:
  application:
    name: CertaBotNFe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
  jmx:
    enabled: false
  
  datasource:
    url: jdbc:sqlserver://192.168.0.27;databaseName=CertaBotNFeDev;encrypt=false;integratedSecurity=false;
    username: giovanni.andrade
    password: gigi1704

config:
  ip: http://192.168.0.26
