package br.com.certacon.certabotnfefiles.utils;

public enum ProcessStatus {
    CREATED, UPDATED, LOGGED, ERROR, CHANGED, DOWNLOADED, PROXY_ERROR, OK, MOVED, RUNTIME_ERROR, MALFORMULED_ERROR, INTERRUPTED_ERROR, IO_ERROR, READY
}
